
services:
  newwavemocards:
    build: ./backend/
    image: wavemocards-backend:1.6
    container_name: wavemocards_backend
    restart: unless-stopped
    env_file: .env.compose
    # ports:
    #   - 80:80
    volumes:
      - ./backend_code:/backend
    networks:
      - proxy_net
networks:
  proxy_net:
    external: true